import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  cowProtocolSidebar: [
    {
      type: 'category',
      label: 'Protocol (Batch Auctions)',
      link: {
        type: 'doc',
        id: 'cow-protocol/README',
      },
      items: [
        {
          type: 'category',
          label: 'Concepts',
          link: {
            type: 'generated-index',
            title: 'Concepts',
            slug: 'cow-protocol/concepts',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cow-protocol/concepts',
            }
          ]
        },
        {
          type: 'category',
          label: 'Tutorials',
          link: {
            type: 'generated-index',
            title: 'Tutorials',
            slug: 'cow-protocol/tutorials',
          },
          items: [
            {
              type: 'category',
              label: 'CoW Swap',
              link: {
                type: 'doc',
                id: 'cow-protocol/tutorials/cow-swap/README',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cow-protocol/tutorials/cow-swap',
                }
              ]
            },
            {
              type: 'category',
              label: 'CoW Explorer',
              link: {
                type: 'doc',
                id: 'cow-protocol/tutorials/cow-explorer/README',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cow-protocol/tutorials/cow-explorer'
                }
              ]
            },
            {
              type: 'category',
              label: 'Solvers',
              link: {
                type: 'doc',
                id: 'cow-protocol/tutorials/solvers/README'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cow-protocol/tutorials/solvers'
                }
              ]
            },
            {
              type: 'category',
              label: 'Custom integrations',
              link: {
                type: 'doc',
                id: 'cow-protocol/tutorials/integrations/README',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cow-protocol/tutorials/integrations',
                }
              ]
            },
            {
              type: 'category',
              label: 'Analyze auctions',
              link: {
                type: 'doc',
                id: 'cow-protocol/tutorials/analyze/README'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cow-protocol/tutorials/analyze'
                }
              ]
            },  
            {
              type: 'category',
              label: 'Arbitrate auctions',
              link: {
                type: 'doc',
                id: 'cow-protocol/tutorials/arbitrate/README'
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'cow-protocol/tutorials/arbitrate'
                }
              ]
            },  
          ]
        },
        {
          type: 'category',
          label: 'Technical reference',
          link: {
            type: 'generated-index',
            title: 'Technical reference',
            slug: 'cow-protocol/reference',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'cow-protocol/reference'
            }
          ]
        },          
      ],
    },
  ],
  governanceSidebar: [
    {
      type: 'category',
      label: 'DAO Governance',
      link: {
        type: 'doc',
        id: 'governance/README',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'governance'
        }
      ]
    }
  ]
};

module.exports = sidebars;
